server:
  port: 9091
spring:
  application:
    name: auth-service
  messages:
    basename: message, ValidationMessages
    encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6372
      password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

jwt:
  secret: 8e24abc6be9aa115877dca322f1c2a6f3cc3f97c80efa5ee16c2e3bc497141084b2d85a6aa2ae028cad7c7f5e25aa7a42d06028c1c7313ffaa27617f9a5004b8
  access-token:
    expiry:
      seconds: 3600
  refresh-token:
    expiry:
      seconds: 2592000

springdoc:
  api-docs:
    enabled: true
    path: /v1/auth/v3/api-docs

logging:
  level:
    root: INFO
