server:
  port: 9095

spring:
  application:
    name: file-service
  messages:
    basename: message, ValidationMessages
    encoding: UTF-8
  data:
    mongodb:
        uri: mongodb://localhost:27017/FileDB
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

jwt:
  secret: 8e24abc6be9aa115877dca322f1c2a6f3cc3f97c80efa5ee16c2e3bc497141084b2d85a6aa2ae028cad7c7f5e25aa7a42d06028c1c7313ffaa27617f9a5004b8
  access-token:
    expiry:
      seconds: 3600
  refresh-token:
    expiry:
      seconds: 2592000

gcp:
  config:
    file: key.json
  bucket:
    name: e-commerce-d877c.appspot.com
    url: https://storage.googleapis.com/${gcp.bucket.name}/

springdoc:
  api-docs:
    enabled: true
    path: /v1/files/v3/api-docs