server:
  port: 9092

spring:
  application:
    name: product-service
  messages:
    basename: message, ValidationMessages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:6950/ProductDB
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: http://localhost:9200
  batch:
    jdbc:
      initialize-schema: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

jwt:
  secret: 8e24abc6be9aa115877dca322f1c2a6f3cc3f97c80efa5ee16c2e3bc497141084b2d85a6aa2ae028cad7c7f5e25aa7a42d06028c1c7313ffaa27617f9a5004b8
  access-token:
    expiry:
      seconds: 3600
  refresh-token:
    expiry:
      seconds: 2592000

springdoc:
  api-docs:
    enabled: true
    path: /v1/products/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,httptrace
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"
  level:
    com.trkgrn.productservice: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    feign: DEBUG